export const Gamemodes = [
  { "ID": 0, "Name": "Event Mode" },
  { "ID": 3, "Name": "Grand Prix" },
  { "ID": 4, "Name": "Grand Prix '23" },
  { "ID": 5, "Name": "Time Trial" },
  { "ID": 6, "Name": "Splitscreen" },
  { "ID": 7, "Name": "Online Custom" },
  { "ID": 8, "Name": "Online League" },
  { "ID": 11, "Name": "Career Invitational" },
  { "ID": 12, "Name": "Championship Invitational" },
  { "ID": 13, "Name": "Championship" },
  { "ID": 14, "Name": "Online Championship" },
  { "ID": 15, "Name": "Online Weekly Event" },
  { "ID": 17, "Name": "Story Mode" },
  { "ID": 19, "Name": "Career '22" },
  { "ID": 20, "Name": "Career '22 Online" },
  { "ID": 21, "Name": "Career '23" },
  { "ID": 22, "Name": "Career '23 Online" },
  { "ID": 23, "Name": "Driver Career '24" },
  { "ID": 24, "Name": "Career '24 Online" },
  { "ID": 25, "Name": "My Team Career '24" },
  { "ID": 26, "Name": "Curated Career '24" },
  { "ID": 127, "Name": "Benchmark" }
]