export default Teams = [
  {"ID": 0, "Team": "Mercedes"},
  {"ID": 1, "Team": "Ferrari"},
  {"ID": 2, "Team": "Red Bull Racing"},
  {"ID": 3, "Team": "Williams"},
  {"ID": 4, "Team": "Aston Martin"},
  {"ID": 5, "Team": "Alpine"},
  {"ID": 6, "Team": "RB"},
  {"ID": 7, "Team": "Haas"},
  {"ID": 8, "Team": "McLaren"},
  {"ID": 9, "Team": "Sauber"},
  {"ID": 41, "Team": "F1 Generic"},
  {"ID": 104, "Team": "F1 Custom Team"},
  {"ID": 143, "Team": "Art GP '23"},
  {"ID": 144, "Team": "Campos '23"},
  {"ID": 145, "Team": "Carlin '23"},
  {"ID": 146, "Team": "PHM '23"},
  {"ID": 147, "Team": "Dams '23"},
  {"ID": 148, "Team": "Hitech '23"},
  {"ID": 149, "Team": "MP Motorsport '23"},
  {"ID": 150, "Team": "Prema '23"},
  {"ID": 151, "Team": "Trident '23"},
  {"ID": 152, "Team": "Van Amersfoort Racing '23"},
  {"ID": 153, "Team": "Virtuosi '23"}
];