export const Tracks = [
  { "ID": 0, "Track": "Melbourne" },
  { "ID": 1, "Track": "Paul Ricard" },
  { "ID": 2, "Track": "Shanghai" },
  { "ID": 3, "Track": "Sakhir (Bahrain)" },
  { "ID": 4, "Track": "Catalunya" },
  { "ID": 5, "Track": "Monaco" },
  { "ID": 6, "Track": "Montreal" },
  { "ID": 7, "Track": "Silverstone" },
  { "ID": 8, "Track": "Hockenheim" },
  { "ID": 9, "Track": "Hungaroring" },
  { "ID": 10, "Track": "Spa" },
  { "ID": 11, "Track": "Monza" },
  { "ID": 12, "Track": "Singapore" },
  { "ID": 13, "Track": "Suzuka" },
  { "ID": 14, "Track": "Abu Dhabi" },
  { "ID": 15, "Track": "Texas" },
  { "ID": 16, "Track": "Brazil" },
  { "ID": 17, "Track": "Austria" },
  { "ID": 18, "Track": "Sochi" },
  { "ID": 19, "Track": "Mexico" },
  { "ID": 20, "Track": "Baku (Azerbaijan)" },
  { "ID": 21, "Track": "Sakhir Short" },
  { "ID": 22, "Track": "Silverstone Short" },
  { "ID": 23, "Track": "Texas Short" },
  { "ID": 24, "Track": "Suzuka Short" },
  { "ID": 25, "Track": "Hanoi" },
  { "ID": 26, "Track": "Zandvoort" },
  { "ID": 27, "Track": "Imola" },
  { "ID": 28, "Track": "Portimão" },
  { "ID": 29, "Track": "Jeddah" },
  { "ID": 30, "Track": "Miami" },
  { "ID": 31, "Track": "Las Vegas" },
  { "ID": 32, "Track": "Losail" }
]